### ISSUE TITLE
Why use `stream.meta.answers.pm` instead of `ctx.answers.pm`?

### ISSUE THREAD

**Issue by niftylettuce** [egoist/template-nm#15]
https://github.com/egoist/template-nm/blob/master/sao.js#L106

**Comment by egoist** [comment]
hmm yeah they're equivalent, should use that instead.

**Comment by niftylettuce** [comment]
@egoist no they aren't apparently, `answers` is undefined in `ctx`, it's only accessible by stream?  I think you need to revert

**Comment by niftylettuce** [comment]
@egoist you can prob switch it now and close this issue once you upgrade to latest version of sao

also you might want to move these templates to the @saojs org

**Comment by egoist** [comment]
someone might use old SAO with this template, so I won't switch it for now.

And I don't think we need to move templates to the @saojs, they're not really related to SAO, for example: template-electron / template-gitignore
