### ISSUE TITLE
Prompt to add CLI

### ISSUE THREAD

**Issue by tiaanduplessis** [egoist/template-nm#7]
Could be useful. Would be happy to do the PR.

**Comment by egoist** [comment]
Sure, PR is welcome. I've thought about this too and I used to using meow but I use yargs more these days, do you have any suggestions on this?

**Comment by tiaanduplessis** [comment]
I think yargs is the way to go 👍

**Comment by egoist** [comment]
@tiaanduplessis sounds good to me as well 👏

**Comment by egoist** [comment]
Landed in `v0.13.0`
